import { BaseField } from "../types/types";

export const AUDIT_AND_COMPLIANCE_DB: BaseField[] = [
    {
        label: "Software Name",
        fieldType: "text",
        name: "softwarename",
        placeholder: "Select Employee",
        isRequired: true,
        visible: false,
        options: [],
        defaultValue: [],
        selectAll: true,
        show: true,
    },
    {
        label: "Auditor Name",
        fieldType: "text",
        name: "auditorname",
        placeholder: "",
        isRequired: true,
        visible: false,
        options: [],
        defaultValue: [],
        selectAll: true,
        show: true,
    },
    {
        label: "Audit Date",
        fieldType: "date",
        name: "auditDate",
        placeholder: "Pick a date",
        isRequired: true,
        format: "DD-MM-YYYY",
        disabled: false,
    },
    {
        label: "Licenses Purchased",
        fieldType: "text",
        name: "licensepurchased",
        placeholder: "",
        isRequired: true,
        visible: false,
        options: [],
        defaultValue: [],
        selectAll: true,
        show: true,
    },
    {
        label: "Licenses in Use",
        fieldType: "text",
        name: "licensesinuse",
        placeholder: "",
        isRequired: true,
        visible: false,
        options: [],
        defaultValue: [],
        selectAll: true,
        show: true,
    },
    {
        label: "",
        fieldType: "checkbox",
        name: "ckbox",
        placeholder: "",
    },
    {
        label: 'Non-compliance Issues',
        placeholder: "Descrine any compliance issue found...",
        defaultValue: '',
        isRequired: false,
        name: "noncomplianceissues",
        fieldType: 'textarea',
        // maxLength: 500,
        className: "border-[rgb(226, 232, 240)]"
    },
    {
        label: 'Actions Taken',
        placeholder: "Descrine remediation actions",
        defaultValue: '',
        isRequired: false,
        name: "actionstaken",
        fieldType: 'textarea',
        // maxLength: 500,
        className: "border-[rgb(226, 232, 240)]"
    },
    {
        label: "Upload Files",
        fieldType: "upload",
        name: "FileUploadURLs",
        isRequired: false,
        filelist: [],
        maxCount: Infinity,
        check: [
            ".doc", ".docx", ".odt", ".pdf", ".tex", ".txt", ".xls", ".xlsx",
            ".jpg", ".jpeg", ".png", ".pptx", ".rtf", ".wpd", "._zip"
        ],
        accept: ".doc,.docx,.odt,.pdf,.tex,.txt,.xls,.xlsx,.jpg,.jpeg,.png,.pptx,.rtf,.wpd,._zip",
        info: "Files allowed to Upload are .doc,.docx,.odt,.pdf,.tex,.txt,.rtf,.xls,.xlsx,.wpd,.jpg,.jpeg,.png,.pptx,._zip.",
        disabled: false
    },
]