import { BaseField } from "../types/types";

export const CONFIGURATION_DB:BaseField[]=[
    {
        name:'CustomerFieldinMyRequest',
        fieldType:'checkbox',
        label:'Display Customer Field in Create Service Request',
        defaultChecked:false,
    },
    {
        name:'AssetFieldinCreateEditServiceRequest',
        fieldType:'checkbox',
        label:'Display Asset Field in Create Service Request',
        defaultChecked:true,
    },
    {
        name:'IsDefaultNotifyUsers',
        fieldType:'checkbox',
        label:'Notify below Users On Service Request Edit',
        defaultChecked:true, 
    },
    {
        label: "",
        fieldType: "multiselect",
        name: "NotifyUserTypes",
        placeholder: "Select User",
        isRequired: false,
        options:[],
        defaultValue:[],
        selectAll:true,
        show:false,
        dependsOn:'IsDefaultNotifyUsers'
    },
    {
        name:'AllowWorkOrderCreation',
        fieldType:'checkbox',
        label:'Allow Work Order Creation',
        defaultChecked:true,
    },
    {
        name:'PauseSLAcalculation',
        fieldType:'checkbox',
        label:'Pause SLA calculation',
        defaultChecked:false,
    },
    {
        label: "Service Request Status List",
        fieldType: "multiselect",
        name: "DefaultSLAStatusDataList",
        placeholder: "Select Service Request Status",
        isRequired: false,
        options: [{ label: 'Open', value: 'open' }, { label: 'In Progress', value: 'in_progress' }, { label: 'Closed', value: 'closed' }],
        defaultValue:[],
        selectAll:true,
        show:false,
        dependsOn:'PauseSLAcalculation'
    },
    {
        name:'ServiceRequestType',
        label:'Service Request Type',
        fieldType:'text',
        isRequired:true,
        placeholder:'Enter Service Request Type',
    },
    {
        label: "User Group",
        fieldType: "multiselect",
        name: "UserGroup",
        placeholder: "Select User Group",
        isRequired: false,
        options: [],
        selectAll:true,
    },
    {
        label: "Vendor",
        fieldType: "multiselect",
        name: "Vendor",
        placeholder: "Select Vendor",
        isRequired: false,
        options: [],
        selectAll:true,
    },
    {
        name:'SLAHoursMinutes',
        label:'SLA Hours/Minutes',
        fieldType:'text',
        isRequired:false,
        placeholder:'HH:MM',
        validationPattern: "^\\d+:[0-5]\\d$",
        patternErrorMessage:'Please enter time in HH:MM format (e.g., 12:30)'
    },
    {
        name:'ReminderForSLA',
        label:'Reminder For SLA',
        fieldType:'text',
        isRequired:false,
        placeholder:'HH:MM',
        validationPattern: "^\\d+:[0-5]\\d$",
        patternErrorMessage:'Please enter time in HH:MM format (e.g., 12:30)'
    },
    {
        label: "Escalation To",
        fieldType: "multiselect",
        name: "EscalationTo",
        placeholder: "Select Escalation To",
        isRequired: false,
        options: [],
        selectAll:true,
    },
    {
        label: "Set Status To Calculate SLA",
        fieldType: "dropdown",
        name: "SetStatusToCalculateSLA",
        placeholder: "Select Status",
        isRequired: false,
        options: [],
        selectAll:true,
    },
    {
        label: "Service Request Type Admin",
        fieldType: "multiselect",
        name: "ServiceRequestTypeAdmin",
        placeholder: "Select Service Request Type Admin",
        isRequired: false,
        options: [],
        defaultValue:[],
        value: [],
        selectAll:true,
        groupSelectAll:true,
        groupedOptions: [],
    },
    {
        name: 'Description',
        label: 'Description',
        fieldType: 'textarea',
        placeholder: 'Enter Description',
        isRequired: false,
    },
    {
        name: 'Status',
        label: 'Status Type',
        fieldType: 'text',
        placeholder: 'Enter Status Type',
        isRequired: true,
    }

]