import { BaseField } from "../types/types";

export const ITEM_CATEGORY_DB: BaseField[] = [
    {
        label: 'Name',
        fieldType: 'text',
        name: 'name',
        isRequired: true,
        placeholder: '',
        className: 'flex h-10 w-full rounded-md border border-input bg-white px-3 py-2 text-base ring-offset-background',
    },
    {
        label: 'Code',
        fieldType: 'text',
        name: 'code',
        isRequired: true,
        placeholder: '',
        className: 'flex h-10 w-full rounded-md border border-input bg-white px-3 py-2 text-base ring-offset-background',
    },
    {
        label: "Unit Of Measure",
        fieldType: "dropdown",
        name: "unitofmeasure",
        placeholder: "",
        isRequired: true,
        visible: false,
        options: [],
        show: true,
        allowClear: true,
        className: 'flex h-10 w-full rounded-md border border-input bg-white px-3 py-2 text-base ring-offset-background',
    },
    {
        label: 'Description',
        fieldType: 'text',
        name: 'description',
        placeholder: '',
        className: 'flex h-10 w-full rounded-md border border-input bg-white px-3 py-2 text-base ring-offset-background',
    },
        {
        label: '',
        fieldType: 'dropdown',
        name: 'mainCatdropdown',
        placeholder: "Select Main Category",
        isRequired: false,
        options: [],
        selectAll: true
    },
    {
        label: 'Name',
        fieldType: 'text',
        name: 'subname',
        isRequired: true,
        placeholder: '',
        className: 'flex h-10 w-full rounded-md border border-input bg-white px-3 py-2 text-base ring-offset-background',
    },
    {
        label: 'Code',
        fieldType: 'text',
        name: 'subcode',
        isRequired: true,
        placeholder: '',
        className: 'flex h-10 w-full rounded-md border border-input bg-white px-3 py-2 text-base ring-offset-background',
    },
    {
        label: "Unit Of Measure",
        fieldType: "dropdown",
        name: "subunitofmeasure",
        placeholder: "Select UOM",
        isRequired: true,
        visible: false,
        options: [],
        // defaultValue: [],
        // selectAll: true,
        show: true,
        allowClear: true,
        className: 'flex h-10 w-full rounded-md border border-input bg-white px-3 py-2 text-base ring-offset-background',
    },
    {
        label: 'Description',
        fieldType: 'text',
        name: 'subdescription',
        placeholder: '',
        className: 'flex h-10 w-full rounded-md border border-input bg-white px-3 py-2 text-base ring-offset-background',
    },
];