import { BaseField } from "../types/types";

export const SOFTWARE_DB: BaseField[] = [
      {
        label: "Employee ID",
        fieldType: "dropdown",
        name: "employeeID",
        placeholder: "Select Employee",
        isRequired: true,
        visible: false,
        options: [],
        defaultValue: [],
        selectAll: true,
        show: true,
    },
    {
        label: "Department",
        fieldType: "dropdown",
        name: "department",
        placeholder: "Select Department",
        isRequired: true,
        visible: false,
        options: [],
        defaultValue: [],
        selectAll: true,
        show: true,
    },
    {
        label: "Software",
        fieldType: "dropdown",
        name: "software",
        placeholder: "Select Software",
        isRequired: true,
        options: [],
        defaultValue: [],
        selectAll: true,
        show: true,
    },
    {
        label: "Available Licenses",
        fieldType: "dropdown",
        name: "Licenses",
        placeholder: "Select License",
        isRequired: true,
        options: [],
        defaultValue: [],
        selectAll: true,
        show: true,
    },
    {
        label: "Assignment Date",
        fieldType: "date",
        name: "assignmentDate",
        placeholder: "Pick a date",
        isRequired: true,
        format: "DD-MM-YYYY",
        disabled: false,
    },
    {
        label: 'Description',
        placeholder: "Enter Description",
        defaultValue: '',
        isRequired: false,
        name: "description",
        fieldType: 'textarea',
        maxLength: 500,
        className: "border-[rgb(226, 232, 240)]"
    }
]