import { formatDate } from "date-fns";
import { BaseField } from "../types/types";
 
export const SERVICE_DESK_DB: BaseField[] = [
    {
        label: "Service Request Type",
        fieldType: "multiselect",
        name: "ServiceRequestType",
        placeholder: "Select Service Request Type",
        isRequired: false,
        visible: false,
        options: [],
        defaultValue: [],
        selectAll: true,
        show: true,
        jsontype: 'servicerequestDetails'
    },
    {
        label: "Service Request",
        fieldType: "multiselect",
        name: "ServiceRequest",
        placeholder: "Select Service Request",
        isRequired: false,
        visible: false,
        options: [],
        defaultValue: [],
        selectAll: true,
        show: true,
        jsontype: 'servicerequestDetails'
    },
    {
        label: "Select Status",
        fieldType: "multiselect",
        name: "Status",
        placeholder: "Select Status",
        isRequired: false,
        visible: false,
        options: [],
        defaultValue: [],
        selectAll: true,
        show: true,
        jsontype: 'servicerequestDetails'
    },
    {
        label: "Requested By",
        fieldType: "multiselect",
        name: "RequestedBy",
        placeholder: "Select Requested Status",
        isRequired: false,
        visible: false,
        options: [],
        defaultValue: [],
        selectAll: true,
        show: true,
        jsontype: 'servicerequestDetails'
    },
    {
        label: "Requested Date",
        fieldType: "date",
        name: "RequestedDate",
        placeholder: "Select Date",
        isRequired: false,
        //   defaultValue: formatDate(new Date()),
        format: "DD-MM-YYYY",
        disabled: true,
        jsontype: 'servicerequestDetails'
    },
    {
        label: "Company",
        fieldType: "multiselect",
        name: "LevelFiveCompany",
        placeholder: "Select Five Level Company",
        isRequired: false,
        visible: false,
        options: [],
        defaultValue: [],
        selectAll: true,
        show: true,
        jsontype: 'servicerequestDetails'
    },
    {
        label: "Customer",
        fieldType: "multiselect",
        name: "Customer",
        placeholder: "Select Customer",
        isRequired: false,
        visible: false,
        options: [],
        defaultValue: [],
        selectAll: true,
        show: true,
        jsontype: 'servicerequestDetails'
    },
    {
        fieldType: 'treeselect',
        name: 'LevelFiveDepartment',
        label: 'Level Five Department',
        placeholder: 'Type to search files...',
        treeData: [],
        isRequired: false,
        allowClear: true,
        disabled: false,
        errormsg: false,
        jsontype: 'servicerequestDetails'
 
    },
    {
        label: "Assign To",
        fieldType: "multiselect",
        name: "AssignTo",
        placeholder: "Select Assignee",
        isRequired: false,
        options: [],
        defaultValue: [],
        value: [],
        selectAll: true,
        groupSelectAll: true,
        groupedOptions: [],
        disabled: false,
        jsontype: 'servicerequestDetails'
    },
    {
        label: "Severity",
        fieldType: "multiselect",
        name: "Severity",
        placeholder: "Select Severity",
        isRequired: false,
        visible: false,
        options: [],
        defaultValue: [],
        selectAll: true,
        show: true,
        jsontype: 'servicerequestDetails'
    },
    {
        label: "Priority",
        fieldType: "multiselect",
        name: "Priority",
        placeholder: "Select Priority",
        isRequired: false,
        visible: false,
        options: [],
        defaultValue: [],
        selectAll: true,
        show: true,
        jsontype: 'servicerequestDetails'
    },
    {
        name: 'AssetCode',
        label: 'Asset Code',
        fieldType: 'text',
        placeholder: 'Assigned to',
        isRequired: false,
        jsontype: 'servicerequestDetails'
    },
    {
        label: "Main Category",
        fieldType: "dropdown",
        name: "MainCategory",
        placeholder: "Select Main Category",
        isRequired: false,
        visible: false,
        options: [],
        // defaultValue: [],
        selectAll: true,
        show: true,
        allowClear: true,
        jsontype: 'servicerequestDetails'
    },
    {
        label: "Sub Category",
        fieldType: "multiselect",
        name: "SubCategory",
        placeholder: "Select Sub Category",
        isRequired: false,
        visible: false,
        options: [],
        defaultValue: [],
        selectAll: true,
        show: true,
        jsontype: 'servicerequestDetails'
    },
    {
        label: "Date Range",
        fieldType: "rangepicker",
        name: "dateRange",
        // placeholder: ['Start Date', 'End Date'],
        isRequired: false,
        visible: true,
        allowClear: true,
        format: "DD/MM/YYYY",
        defaultValue: null,
        disabled: false,
        tooltip: "Pick a start and end date",
        show: true,
        jsontype: 'servicerequestDetails'
    },
    {
        label: "SLA Status",
        fieldType: "multiselect",
        name: "slastatus",
        placeholder: "Select SLA Status",
        isRequired: false,
        visible: false,
        options: [],
        defaultValue: [],
        selectAll: true,
        show: true,
        jsontype: "slaViolated"
    },
    {
        label: "Assigned To",
        fieldType: "multiselect",
        name: "assignedto",
        placeholder: "Select SLA Status",
        isRequired: false,
        visible: false,
        options: [],
        defaultValue: [],
        selectAll: true,
        show: true,
        jsontype: "slaViolated"
 
    },
    {
        label: "Select Service Request Type",
        fieldType: "multiselect",
        name: "serviceReqTypeSLA",
        placeholder: "Select Service Request Type",
        isRequired: false,
        visible: false,
        options: [],
        defaultValue: [],
        selectAll: true,
        show: true,
        jsontype: "slaViolated"
 
    },
    {
        label: "Service Request No",
        fieldType: "multiselect",
        name: "servicereqno",
        placeholder: "Select Service Request",
        isRequired: false,
        visible: false,
        options: [],
        defaultValue: [],
        selectAll: true,
        show: true,
        jsontype: "slaViolated"
 
    },
    {
        fieldType: 'treeselect',
        name: 'LevelFiveCompanyinSLA',
        label: 'Level Five Company',
        placeholder: 'Select Level Five Company',
        treeData: [],
        isRequired: false,
        allowClear: true,
        disabled: false,
        errormsg: false,
        jsontype: "slaViolated"
 
    },
    {
        fieldType: 'treeselect',
        name: 'levelfivedepartmentINsla',
        label: 'Level Five Department',
        placeholder: 'Type to search files...',
        treeData: [],
        isRequired: false,
        allowClear: true,
        disabled: false,
        errormsg: false,
        jsontype: "slaViolated"
    },
    {
        label: "Customer",
        fieldType: "multiselect",
        name: "Customersla",
        placeholder: "Select Customer",
        isRequired: false,
        visible: false,
        options: [],
        defaultValue: [],
        selectAll: true,
        show: true,
        jsontype: "slaViolated"
 
    },
    {
        label: "Date Range",
        fieldType: "rangepicker",
        name: "dateRangeinSLA",
        // rangeplaceholder: ['Start Date', 'End Date'],
        isRequired: false,
        visible: true,
        allowClear: true,
        format: "DD/MM/YYYY",
        defaultValue: null,
        disabled: false,
        tooltip: "Pick a start and end date",
        show: true,
        jsontype: "slaViolated"
    },
    {
        label: "Requested By",
        fieldType: "multiselect",
        name: "slarequestedby",
        placeholder: "Select Requested Status",
        isRequired: false,
        visible: false,
        options: [],
        defaultValue: [],
        selectAll: true,
        show: true,
        jsontype: "slaViolated"
    },
    {
        label: "Select Status",
        fieldType: "multiselect",
        name: "statusinSLA",
        placeholder: "Select Status",
        isRequired: false,
        visible: false,
        options: [],
        defaultValue: [],
        selectAll: true,
        show: true,
        jsontype: "slaViolated"
    },
    {
        label: "Severity",
        fieldType: "multiselect",
        name: "severityinSLA",
        placeholder: "Select Severity",
        isRequired: false,
        visible: false,
        options: [],
        defaultValue: [],
        selectAll: true,
        show: true,
        jsontype: "slaViolated"
    },
    {
        label: "Priority",
        fieldType: "multiselect",
        name: "priorityinSLA",
        placeholder: "Select Priority",
        isRequired: false,
        visible: false,
        options: [],
        defaultValue: [],
        selectAll: true,
        show: true,
        jsontype: "slaViolated"
    },
    {
        name: 'assetcode',
        label: 'Asset Code',
        fieldType: 'text',
        placeholder: 'Assigned to',
        isRequired: false,
        jsontype: "slaViolated"
    },
    {
        label: "Main Category",
        fieldType: "dropdown",
        name: "maincategoryinSLA",
        placeholder: "Select Main Category",
        isRequired: false,
        visible: false,
        options: [],
        // defaultValue: [],
        allowClear:true,
        selectAll: true,
        show: true,
        jsontype: "slaViolated"
    },
    {
        label: "Sub Category",
        fieldType: "multiselect",
        name: "subcategoryinSLA",
        placeholder: "Select Sub Category",
        isRequired: false,
        visible: false,
        options: [],
        defaultValue: [],
        selectAll: true,
        show: true,
        jsontype: "slaViolated"
    },
    {
        label: "Service Request Detail History",
        fieldType: "dropdown",
        name: "ServiceRequestDetailHistory",
        placeholder: "Select Service Request",
        isRequired: false,
        options: [],
        allowClear: true,
        jsontype: 'serviceReqHistoryDetail'
    },
];
 
 
// export const SERVICE_DESK_SLA_VIOLATED_MET_DB: BaseField[] = [
//     {
//         label: "SLA Status",
//         fieldType: "multiselect",
//         name: "slastatus",
//         placeholder: "Select SLA Status",
//         isRequired: true,
//         visible: false,
//         options: [],
//         defaultValue: [],
//         selectAll: true,
//         show: true,
//         jsontype:"slaViolated"
//     },
//     {
//         label: "Assigned To",
//         fieldType: "multiselect",
//         name: "assignedto",
//         placeholder: "Select SLA Status",
//         isRequired: true,
//         visible: false,
//         options: [],
//         defaultValue: [],
//         selectAll: true,
//         show: true,
//         jsontype:"slaViolated"
 
//     },
//     {
//         label: "Select Service Request Type",
//         fieldType: "multiselect",
//         name: "servicereqType",
//         placeholder: "Select Service Request Type",
//         isRequired: true,
//         visible: false,
//         options: [],
//         defaultValue: [],
//         selectAll: true,
//         show: true,
//         jsontype:"slaViolated"
 
//     },
//     {
//         label: "Service Request No",
//         fieldType: "multiselect",
//         name: "servicereqno",
//         placeholder: "Select Service Request",
//         isRequired: true,
//         visible: false,
//         options: [],
//         defaultValue: [],
//         selectAll: true,
//         show: true,
//         jsontype:"slaViolated"
 
//     },
//     {
//         fieldType: 'treeselect',
//         name: 'LevelFiveCompany',
//         label: 'Level Five Company',
//         placeholder: 'Select Level Five Company',
//         treeData: [],
//         isRequired: true,
//         allowClear: true,
//         disabled: false,
//         errormsg: false,
//         jsontype:"slaViolated"
 
//     },
//     {
//         label: "Customer",
//         fieldType: "multiselect",
//         name: "Customer",
//         placeholder: "Select Customer",
//         isRequired: true,
//         visible: false,
//         options: [],
//         defaultValue: [],
//         selectAll: true,
//         show: true,
//         jsontype:"slaViolated"
 
//     },
//     {
//         label: "Date Range",
//         fieldType: "rangepicker",
//         name: "dateRange",
//         rangeplaceholder: ['Start Date', 'End Date'],
//         isRequired: true,
//         visible: true,
//         allowClear: true,
//         format: "DD/MM/YYYY",
//         defaultValue: null,
//         disabled: false,
//         tooltip: "Pick a start and end date",
//         show: true,
//         jsontype:"slaViolated"
//     },
//     {
//         label: "Requested By",
//         fieldType: "multiselect",
//         name: "slarequestedby",
//         placeholder: "Select Requested Status",
//         isRequired: true,
//         visible: false,
//         options: [],
//         defaultValue: [],
//         selectAll: true,
//         show: true,
//         jsontype:"slaViolated"
//     },
//     {
//         label: "Select Status",
//         fieldType: "multiselect",
//         name: "status",
//         placeholder: "Select Status",
//         isRequired: true,
//         visible: false,
//         options: [],
//         defaultValue: [],
//         selectAll: true,
//         show: true,
//         jsontype:"slaViolated"
//     },
//     {
//         label: "Severity",
//         fieldType: "multiselect",
//         name: "severity",
//         placeholder: "Select Severity",
//         isRequired: true,
//         visible: false,
//         options: [],
//         defaultValue: [],
//         selectAll: true,
//         show: true,
//         jsontype:"slaViolated"
//     },
//     {
//         label: "Priority",
//         fieldType: "multiselect",
//         name: "priority",
//         placeholder: "Select Priority",
//         isRequired: true,
//         visible: false,
//         options: [],
//         defaultValue: [],
//         selectAll: true,
//         show: true,
//         jsontype:"slaViolated"
//     },
//     {
//         name: 'assetcode',
//         label: 'Asset Code',
//         fieldType: 'text',
//         placeholder: 'Assigned to',
//         isRequired: false,
//         jsontype:"slaViolated"
//     },
//     {
//         label: "Main Category",
//         fieldType: "multiselect",
//         name: "maincategory",
//         placeholder: "Select Main Category",
//         isRequired: true,
//         visible: false,
//         options: [],
//         defaultValue: [],
//         selectAll: true,
//         show: true,
//         jsontype:"slaViolated"
//     },
//     {
//         label: "Sub Category",
//         fieldType: "multiselect",
//         name: "subcategory",
//         placeholder: "Select Sub Category",
//         isRequired: true,
//         visible: false,
//         options: [],
//         defaultValue: [],
//         selectAll: true,
//         show: true,
//         jsontype:"slaViolated"
//     },
//     {
//         fieldType: 'treeselect',
//         name: 'levelfivedepartment',
//         label: 'Level Five Department',
//         placeholder: 'Type to search files...',
//         treeData: [],
//         isRequired: true,
//         allowClear: true,
//         disabled: false,
//         errormsg: false,
//         jsontype:"slaViolated"
//     },
// ]
 
// export const SERVICE_REQ_DETAIL_HISTORY_DB: BaseField[] = [
//     {
//         label: "Service Request Detail History",
//         fieldType: "dropdown",
//         name: "ServiceRequestDetailHistory",
//         placeholder: "Select Service Request",
//         isRequired: true,
//         options: [],
//         allowClear: true,
//     },
// ]
 